"""Change genres to ARRAY

Revision ID: f4c8ab3a8057
Revises: cb5bbbd180fa
Create Date: 2021-11-01 20:35:33.593062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c8ab3a8057'
down_revision = 'cb5bbbd180fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120), type_=sa.ARRAY(sa.String()), postgresql_using='genres::character varying[]',
               nullable=False)
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120), type_=sa.ARRAY(sa.String()), postgresql_using='genres::character varying[]',
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
